export const GB_ROLES = {
  BUYER: "BUYER",
  VENDOR: "VENDOR",
  ADMIN: "ADMIN",
} as const;

export const GB_APPROVAL_STATUS = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  NEEDS_REVISION: "NEEDS_REVISION",
} as const;

export const GB_ORDER_STATUS = {
  PENDING_PAYMENT: "PENDING_PAYMENT",
  RESERVED_COD: "RESERVED_COD",
  CAMPAIGN_ACTIVE: "CAMPAIGN_ACTIVE",
  SUCCEEDED: "SUCCEEDED",
  FAILED: "FAILED",
  CANCELLED: "CANCELLED",
} as const;

export const GB_CAMPAIGN_OUTCOME = {
  ACTIVE: "ACTIVE",
  AWAITING_DECISION: "AWAITING_DECISION",
  SUCCEEDED: "SUCCEEDED",
  FAILED: "FAILED",
} as const;

export const GB_DEPOSIT_PERCENT = Number(process.env.GB_DEPOSIT_PERCENT || "5");
